[font]
size = 14.0

[font.normal]
family = "Caskaydia Cove Nerd Font"
style = "Regular"

[window]
dimensions = { columns = 120, lines = 30 }
opacity = 0.8

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true

[cursor.style]
shape = "Underline"   
blinking = "Always"      

[colors.primary]
foreground = "#e6edf3"
background = "#010409"

[colors.cursor]
text = "#010409"
cursor = "#e6edf3"

[colors.selection]
text = "#e6edf3"
background = "#264f78"

[colors.normal]
black = "#484f58"
red = "#ff7b72"
green = "#3fb950"
yellow = "#d29922"
blue = "#58a6ff"
magenta = "#bc8cff"
cyan = "#39c5cf"
white = "#b1bac4"

[colors.bright]
black = "#6e7681"
red = "#ffa198"
green = "#56d364"
yellow = "#e3b341"
blue = "#79c0ff"
magenta = "#d2a8ff"
cyan = "#56d4dd"
white = "#ffffff"
