format = """
[](#a3aed2)\
$os\
[](fg:#a3aed2 bg:#769ff0)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
[](fg:#394260 bg:#283042)\
$python\
$nodejs\
$rust\
$golang\
$php\
[](fg:#283042 bg:#1d2230)\
$docker_context\
[](fg:#1d2230)\
$fill\
[](fg:#1d2230)\
$time\
$cmd_duration\
[](fg:#1d2230)
$line_break\
$character"""

[os]
format = "[($symbol)]($style)"
style = "bg:#a3aed2 fg:#090c0c"
disabled = false

[username]
show_always = true
style_user = "bg:#a3aede fg:#090c0c"
style_root = "bg:#a3aede fg:#090c0c"
format = '[ $user ]($style)'

[directory]
home_symbol = " "
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 1
truncate_to_repo = true

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[character]
disabled = false
success_symbol = '[➜](fg:white)'
error_symbol = '[➜](fg:red)'

[python]
symbol = "  "
style = "bg:#283042"
format = '[[ $symbol](fg:#769ff0 bg:#283042)]($style)'

[nodejs]
symbol = ""
style = "bg:#283042"
format = '[[ $symbol](fg:#769ff0 bg:#283042)]($style)'

[lua]
symbol = " "
style = "bg:#283042"
format = '[[ $symbol](fg:#769ff0 bg:#283042)]($style)'

[rust]
symbol = "󱘗 "
style = "bg:#283042"
format = '[[ $symbol](fg:#769ff0 bg:#283042)]($style)'

[golang]
symbol = ""
style = "bg:#283042"
format = '[[ $symbol](fg:#769ff0 bg:#283042)]($style)'

[php]
symbol = ""
style = "bg:#283042"
format = '[[ $symbol](fg:#769ff0 bg:#283042)]($style)'

[docker_context]
symbol = ""
style = "bg:#1d2230"
format = '[[ $symbol( $context) ](fg:#a0a9cb bg:#1d2230))]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[cmd_duration]
style = "bg:#1d2230"
format = "[ ]($style)"

[fill]
symbol = ' ' 

[os.symbols]
Arch = "  "
Debian = "  "
Fedora = "  "
Linux = "  "
Macos = "  "